In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
x, y = np.arange(10).reshape((5,2)), range(5)

In [7]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
list(y)

[0, 1, 2, 3, 4]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3)

In [11]:
x_train

array([[2, 3],
       [8, 9],
       [6, 7]])

In [12]:
y_train

[1, 4, 3]

In [13]:
x_test

array([[4, 5],
       [0, 1]])

In [14]:
y_test

[2, 0]

In [15]:
model.fit(x_train,y_train)

LinearRegression(normalize=True)

In [16]:
predictions = model.predict(x_test)

In [17]:
print(predictions)

[2.00000000e+00 3.88578059e-16]


In [1]:
############################################################################################